# --- Network Definition ---
acl localnet src all

# --- Allow-list ---
# External Domains
acl allowed_domains dstdomain .githubusercontent.com
acl allowed_domains dstdomain .mozilla.org
acl allowed_domains dstdomain .openai.com
acl allowed_domains dstdomain .anthropic.com
acl allowed_domains dstdomain .googleapis.com
acl allowed_domains dstdomain .claude.com
acl allowed_domains dstdomain .claude.ai
acl allowed_domains dstdomain .opencode.ai
acl allowed_domains dstdomain .groq.com
acl allowed_domains dstdomain .openrouter.ai
acl allowed_domains dstdomain .cerebras.ai
acl allowed_domains dstdomain .fireworks.ai
acl allowed_domains dstdomain .chatgpt.com
acl allowed_domains dstdomain .cline.bot
acl allowed_domains dstdomain .pi.dev
acl allowed_domains dstdomain .releases.astral.sh

# added for python kernel (prime-agent)
acl allowed_domains dstdomain .pypi.org
acl allowed_domains dstdomain .pythonhosted.org

# package installation
acl allowed_domains dstdomain .registry.npmjs.org
acl allowed_domains dstdomain .github.com
acl allowed_domains dstdomain .rust-lang.org

# Local LLM (Replace with your server's IP or internal hostname)
acl local_llm dst 192.168.1.30
acl local_llm dst 192.168.1.16
acl local_llm dst 127.0.0.1

# --- Access Rules ---
# Allow the listed items
http_access allow allowed_domains
http_access allow local_llm

# Deny everything else
http_access deny all

# --- Security & Stealth ---
http_port 3128
# Hide internal container IPs in the headers for privacy
via off
forwarded_for delete

# Standard log location
# access_log stdio:/var/log/squid/access.log
access_log daemon:/var/log/squid/access.log common

shutdown_lifetime 2 seconds

pid_filename none
